SET NOCOUNT ON;

DECLARE @TuNgay DATE = ?;
DECLARE @DenNgay DATE = ?;

SELECT
    COUNT(1) AS RowCount
FROM dbo.HoSoKhamBenhNgoaiTru WITH (NOLOCK)
WHERE CAST(NgayVaoKham AS DATE) BETWEEN @TuNgay AND @DenNgay;
